version: "3"


services:
  server:
    build: ./server_
    ports:
      - 8080:8080
    networks:
      - webnet

  prometheus:
    image: prom/prometheus:v2.40.7
    volumes:
      - ./server_/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - server
    networks:
      - webnet

  grafana:
    image: grafana/grafana:9.4.2
    volumes:
      - ./server_/grafana/config.ini:/etc/grafana/grafana.ini
      - ./server_/grafana/datasource.yml:/etc/grafana/provisioning/datasources/default.yaml
      - ./server_/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./server_/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - server
    networks:
      - webnet


networks:
  webnet:
    driver: bridge
